secrets:
  mistral_api_key:
    file: ./secrets/mistral_api_key.txt
  internal_api_key:
    file: ./secrets/internal_api_key.txt

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    networks:
      - backend
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http      
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure
   
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    networks:
      - backend
    environment:
      ENABLE_CUDA: '0'
    restart: on-failure

  processor:
    networks:
      - backend  
    build: ./processor
    volumes:
      - ./data:/data
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - DATA_FOLDER=/data
    depends_on:
      - weaviate
      - t2v-transformers
    restart: on-failure
    user: "1000:1000"  # Use non-root user
    security_opt:
      - no-new-privileges:true

  api:
    networks:
      - frontend
      - backend
    secrets:
      - mistral_api_key
      - internal_api_key
    build: ./api
    ports:
      - 8000:8000
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - MISTRAL_MODEL=${MISTRAL_MODEL}
      - MISTRAL_DAILY_TOKEN_BUDGET=${MISTRAL_DAILY_TOKEN_BUDGET}
      - MISTRAL_MAX_REQUESTS_PER_MINUTE=${MISTRAL_MAX_REQUESTS_PER_MINUTE}
      - MISTRAL_MAX_TOKENS_PER_REQUEST=${MISTRAL_MAX_TOKENS_PER_REQUEST}
      - ENABLE_CHAT_LOGGING=${ENABLE_CHAT_LOGGING:-false}
      - ANONYMIZE_CHAT_LOGS=${ANONYMIZE_CHAT_LOGS:-true}
      - LOG_RETENTION_DAYS=${LOG_RETENTION_DAYS:-30}
      - CHAT_LOG_DIR=chat_data
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key
    depends_on:
      - weaviate
      - t2v-transformers
    volumes:
      - ./chat_data:/app/chat_data      
    user: "1000:1000"  # Use non-root user
    security_opt:
      - no-new-privileges:true

  web-prototype:
    networks:
      - frontend  
    build: ./web-prototype
    ports:
      - "8501:8501"
    secrets:
      - internal_api_key
    environment:
      - API_URL=http://api:8000
      - ENABLE_CHAT_LOGGING=${ENABLE_CHAT_LOGGING:-false}
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key
    depends_on:
      - api
    volumes:
      - ./web-prototype/.streamlit:/app/.streamlit
    user: "1000:1000"  # Use non-root user
    security_opt:
      - no-new-privileges:true

  web-production:
    networks:
      - frontend   
    build: ./web-production
    ports:
      - "80:80"
    environment:
      - API_URL=http://api:8000
      - ENABLE_CHAT_LOGGING=${ENABLE_CHAT_LOGGING:-false}
    depends_on:
      - api
      - web-prototype
    user: "1000:1000"  # Use non-root user
    security_opt:
      - no-new-privileges:true

volumes:
  weaviate_data: