secrets:
  mistral_api_key:
    file: ./secrets/mistral_api_key.txt
  internal_api_key:
    file: ./secrets/internal_api_key.txt
  jwt_secret_key:
    file: ./secrets/jwt_secret_key.txt

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    networks:
      - backend
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    networks:
      - backend
    environment:
      ENABLE_CUDA: '0'
    restart: on-failure

  processor:
    networks:
      - backend
    build: ./processor
    volumes:
      - ./data:/data
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - DATA_FOLDER=/data
    depends_on:
      - weaviate
      - t2v-transformers
    restart: on-failure
    user: "1000:1000"  # Use non-root user
    security_opt:
      - no-new-privileges:true

  api:
    networks:
      - frontend
      - backend
    secrets:
      - mistral_api_key
      - internal_api_key
      - jwt_secret_key
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - MISTRAL_MODEL=mistral-large-latest
      - MISTRAL_DAILY_TOKEN_BUDGET=100000
      - MISTRAL_MAX_REQUESTS_PER_MINUTE=30
      - MISTRAL_MAX_TOKENS_PER_REQUEST=5000
      - ENABLE_CHAT_LOGGING=true
      - ANONYMIZE_CHAT_LOGS=true
      - LOG_RETENTION_DAYS=30
      - MISTRAL_API_KEY_FILE=/run/secrets/mistral_api_key
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key
      - JWT_SECRET_KEY_FILE=/run/secrets/jwt_secret_key
      - LOG_DIR=/app/logs
      - CHAT_LOG_BUFFER_SIZE=1
      - CHAT_LOG_DIR=/app/chat_data
    depends_on:
      - weaviate
      - t2v-transformers
    volumes:
      - ./chat_data:/app/chat_data
      - ./logs:/app/logs
      - ./users.json:/app/users.json
    user: "1000:1000"  # Use non-root user
    security_opt:
      - no-new-privileges:true

  vue-frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - frontend
    secrets:
      - internal_api_key
    environment:
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key
      - ENABLE_CHAT_LOGGING=true
    depends_on:
      - api
    # user: "1000:1000"  # Use non-root user
    security_opt:
      - no-new-privileges:true

volumes:
  weaviate_data:

