[theme]
base = "light"
# Primary accent for interactive elements
primaryColor = "#2196F3"
# Background color for the main content area
backgroundColor = "#FFFFFF"
# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F5F5F5"
# Color used for almost all text
textColor = "#212121"
# Font family for all text in the app, except code blocks
font = "sans-serif"

# Hide dropdown in the top right corner (a built-in Streamlit menu)
[ui]
hideTopBar = true